export interface GameDefinition {
  id: string
  nameKey: string
  icon: string
  category: "classic" | "pvp"
  implemented: boolean
  route: string
}

export const games: GameDefinition[] = [
  {
    id: "battleship",
    nameKey: "battleship",
    icon: "battleship",
    category: "classic",
    implemented: true,
    route: "/game/battleship",
  },
  {
    id: "tictactoe",
    nameKey: "tictactoe",
    icon: "tictactoe",
    category: "classic",
    implemented: true,
    route: "/game/tictactoe",
  },
  { id: "chess", nameKey: "chess", icon: "chess", category: "classic", implemented: true, route: "/game/chess" },
  {
    id: "checkers",
    nameKey: "checkers",
    icon: "checkers",
    category: "classic",
    implemented: true,
    route: "/game/checkers",
  },
  {
    id: "backgammon",
    nameKey: "backgammon",
    icon: "backgammon",
    category: "classic",
    implemented: true,
    route: "/game/backgammon",
  },
  {
    id: "reversi",
    nameKey: "reversi",
    icon: "reversi",
    category: "classic",
    implemented: true,
    route: "/game/reversi",
  },
  { id: "go", nameKey: "go", icon: "go", category: "classic", implemented: true, route: "/game/go" },
  {
    id: "fifteenPuzzle",
    nameKey: "fifteenPuzzle",
    icon: "fifteenPuzzle",
    category: "classic",
    implemented: true,
    route: "/game/fifteen-puzzle",
  },
  { id: "sudoku", nameKey: "sudoku", icon: "sudoku", category: "classic", implemented: true, route: "/game/sudoku" },
  { id: "bridge", nameKey: "bridge", icon: "bridge", category: "classic", implemented: true, route: "/game/bridge" },
  {
    id: "pokerTexas",
    nameKey: "poker",
    icon: "poker",
    category: "classic",
    implemented: true,
    route: "/game/poker",
  },
  {
    id: "brainGame",
    nameKey: "brainGame",
    icon: "brainGame",
    category: "classic",
    implemented: true,
    route: "/game/brain-game",
  },
  { id: "alias", nameKey: "alias", icon: "alias", category: "classic", implemented: true, route: "/game/alias" },
  {
    id: "charades",
    nameKey: "charades",
    icon: "charades",
    category: "classic",
    implemented: true,
    route: "/game/charades",
  },
  {
    id: "anagrams",
    nameKey: "anagrams",
    icon: "anagrams",
    category: "classic",
    implemented: true,
    route: "/game/anagrams",
  },
  {
    id: "twentyQuestions",
    nameKey: "twentyQuestions",
    icon: "twentyQuestions",
    category: "classic",
    implemented: true,
    route: "/game/twenty-questions",
  },
  {
    id: "pokerDice",
    nameKey: "pokerDice",
    icon: "pokerDice",
    category: "classic",
    implemented: true,
    route: "/game/poker-dice",
  },
  {
    id: "carcassonne",
    nameKey: "carcassonne",
    icon: "carcassonne",
    category: "classic",
    implemented: true,
    route: "/game/carcassonne",
  },
  { id: "uno", nameKey: "uno", icon: "uno", category: "classic", implemented: true, route: "/game/uno" },
  { id: "dots", nameKey: "dots", icon: "dots", category: "classic", implemented: true, route: "/game/dots" },
  {
    id: "bullsAndCows",
    nameKey: "bullsAndCows",
    icon: "bullsAndCows",
    category: "classic",
    implemented: true,
    route: "/game/bulls-cows",
  },
  {
    id: "mastermind",
    nameKey: "mastermind",
    icon: "mastermind",
    category: "classic",
    implemented: true,
    route: "/game/mastermind",
  },
  { id: "blokus", nameKey: "blokus", icon: "blokus", category: "classic", implemented: true, route: "/game/blokus" },
  { id: "hanoi", nameKey: "hanoi", icon: "hanoi", category: "classic", implemented: true, route: "/game/hanoi" },
  {
    id: "tetris",
    nameKey: "tetris",
    icon: "tetris",
    category: "classic",
    implemented: true,
    route: "/game/tetris",
  },
  {
    id: "mathGame",
    nameKey: "mathGame",
    icon: "mathGame",
    category: "classic",
    implemented: true,
    route: "/game/math-game",
  },
]
